import type { Metadata } from "next";
import "./globals.css";
import { Noto_Serif_Bengali } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";

import Navsection from "@/components/HomePages/Navsection/Navsection";
import { Suspense } from "react";
import Loading from "./loading";
// import { AuthProvider } from "@/context/AuthContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["bengali"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-noto-serif-bengali",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        id="__next"
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerifBengali.variable}  antialiased font-noto`}
      >
        <Navsection />

        {/* <AuthProvider>{children}</AuthProvider> */}

        {/* <AuthProvider> */}

        {/* {children} */}
        <section className="mt-12" id="mainSection"> 
        <Suspense fallback={<Loading />} >
          {children}
        </Suspense>
        </section>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
